export enum GameEventTypes {
    CHAT_MESSAGE = 'CHAT_MESSAGE',
    USER_DRAW = "USER_DRAW",
    GAME_OVER = 'GAME_OVER',
    JOIN_GAME = 'JOIN_GAME',
    ROUND_NOTIFICATION = 'ROUND_NOTIFICATION',
    FINISH_GAME = 'FINISH_GAME',
}